---
# tasks file for db-tier
- name: Install postgresql server
  yum:
    name: postgresql-server
    state: latest

- name: Check database initialization
  command: "postgresql-check-db-dir  {{ postgresql_db_dir }}"
  register: check_db_output
  changed_when: check_db_output == 1
  ignore_errors: yes
  
- name: initilize postgresql db if db is not initialized
  shell: postgresql-setup initdb
  when: check_db_output.rc != 0

- name: start and enable postgresql
  service:
    name: postgresql
    enabled: yes
    state: started

...
